"""One-time extraction of the Umpqua FEIS Appendix B yield tables + economics.

Parses the HathiTrust OCR text of the Umpqua National Forest Final
Environmental Impact Statement (FEIS) Appendix B — the FORPLAN analysis
volume — and emits the typed, provenance-stamped package data module
``fresh_daugherty/instance/umpqua_feis.py``. Run once; the emitted module is
committed so the package does not depend on the gitignored scan at runtime.

Source and licensing: the underlying work is a US government (USDA Forest
Service) document, public domain (17 U.S.C. § 105). The HathiTrust/Google
digitized scans and OCR carry Google's request that the images and OCR not be
re-hosted, redistributed, or used commercially — so the raw scans/OCR stay in
the gitignored `tmp/` and are NEVER committed; only the derived, structured,
factual dataset (numbers, which are not copyrightable) is committed. Source:
Umpqua National Forest FEIS Appendix B, HathiTrust record 002439528
(https://catalog.hathitrust.org/Record/002439528), public domain. Companion:
1987 Draft EIS, HathiTrust record 002547999
(https://catalog.hathitrust.org/Record/002547999).

Usage:
    python scripts/extract_umpqua_feis.py <feis_appendix_b_txt_dir> <out_module>

The OCR is line-structured: each yield-table entry is a label line
("Thin @45" / "Regen @115") followed by up to 6 numeric lines (MCF, MBF, DBH
for the volume-emphasis variant, then MCF, MBF, DBH for the PNV-emphasis
variant). CMAI/95%-CMAI markers (* / **) are stripped from the numbers.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Yield-table pages in the FEIS Appendix B OCR text (0-padded page filenames).
YIELD_TABLE_PAGES = [137, 138, 139, 140, 141, 142, 143, 144]

_ENTRY_RE = re.compile(r"^(Thin|Regen)\s*@\s*(\d+)")
_NUM_RE = re.compile(r"^-?[\d.]+\*?\*?$")
_TABLE_RE = re.compile(r"^Table (B-\d+)")
_ECCLASS_RE = re.compile(r"\b(CH-CW|CD-CP|CR-CF|CF-CR|CM-CE)\b")


def _clean_num(tok: str) -> float | None:
    tok = tok.strip().rstrip("*")
    if tok in ("-", "", "$"):
        return None
    try:
        return float(tok)
    except ValueError:
        return None


def parse_yield_tables(txt: str) -> list[dict]:
    """Parse the FEIS Appendix B yield tables into structured records."""
    lines = txt.split("\n")
    tables: list[dict] = []
    i = 0
    current: dict | None = None
    while i < len(lines):
        line = lines[i].strip()
        tm = _TABLE_RE.match(line)
        if tm:
            if current is not None:
                tables.append(current)
            current = {"table": tm.group(1), "title": [], "entries": []}
            i += 1
            continue
        if current is not None:
            em = _ENTRY_RE.match(line)
            if em:
                kind, age = em.group(1), int(em.group(2))
                nums: list[float | None] = []
                j = i + 1
                while j < len(lines) and _NUM_RE.match(lines[j].strip()) and len(nums) < 6:
                    nums.append(_clean_num(lines[j]))
                    j += 1
                current["entries"].append({"kind": kind, "age": age, "values": nums})
                i = j
                continue
            # Accumulate title/label lines (ecoclass, prescription, emphasis).
            if line and not line.startswith("FEIS APPENDIX") and not _NUM_RE.match(line):
                current["title"].append(line)
        i += 1
    if current is not None:
        tables.append(current)
    return tables


def _classify(title_lines: list[str]) -> dict:
    text = " ".join(title_lines)
    em = _ECCLASS_RE.search(text)
    ecoclass = em.group(1) if em else None
    if ecoclass == "CF-CR":
        ecoclass = "CR-CF"
    emphasis = (
        "volume"
        if "Volume Emphasis" in text
        else ("pnv" if "PNV Emphasis" in text or "PNV" in text else None)
    )
    return {"ecoclass": ecoclass, "emphasis": emphasis, "title": text}


def main() -> None:
    src_dir = Path(sys.argv[1])
    out_module = Path(sys.argv[2])
    txt = "\n".join((src_dir / f"{p:08d}.txt").read_text() for p in YIELD_TABLE_PAGES)
    tables = parse_yield_tables(txt)
    for t in tables:
        t.update(_classify(t.pop("title")))

    out_module.parent.mkdir(parents=True, exist_ok=True)
    with open(out_module, "w") as f:
        f.write('"""Umpqua FEIS Appendix B yield tables + economics (extracted).\n')
        f.write("\nAuto-generated by tmp/extract_umpqua_feis.py from the FEIS Appendix B\n")
        f.write("OCR text (public domain; HathiTrust record 002439528). Do not edit by hand.\n")
        f.write('"""\n\n')
        f.write("UMPQUA_YIELD_TABLES = ")
        f.write(repr(tables))
        f.write("\n\n")
        f.write(_ECONOMICS_BLOCK)
    print(f"wrote {out_module}: {len(tables)} yield tables")
    for t in tables:
        print(
            f"  {t['table']}: {t.get('ecoclass')} {t.get('emphasis')} ({len(t['entries'])} entries)"
        )


#: Economics tables (FEIS Appendix B), transcribed from the OCR text:
#: Table B-39 (site indices), Table B-65 (stumpage/logging/manufacturing by
#: species), Table B-66 (Douglas-fir price-diameter/pond values). 1982 dollars.
_ECONOMICS_BLOCK = """
# Table B-39: McArdle (SI100) and King (SI50) site indices by ecoclass.
SITE_INDEX_BY_ECOCLASS = {
    "CH-CW": {"si100": 115, "si50": 88},
    "CD-CP": {"si100": 107, "si50": 82},
    "CR-CF": {"si100": 119, "si50": 89},
    "CM-CE": None,  # mountain hemlock: separate Johnson TMCUAN curve, no DFSIM SI
}

# Table B-65: stumpage / logging / manufacturing costs ($/MBF, 1982 dollars)
# and the board-foot/cubic-foot (BF/CF) conversion and average DBH.
# (stumpage, logging, manufacturing, bf_per_cf, avg_dbh_in)
SPECIES_ECONOMICS = {
    "Douglas-Fir": (255.0, 134.0, 206.0, 5.91, 27.5),
    "W. Red Cedar": (112.0, 137.0, 167.0, 5.5, 22.5),
    "Incense Cedar": (107.0, 138.0, 160.0, 5.13, 19.5),
    "Western Hemlock": (73.0, 127.0, 153.0, 5.24, 20.4),
    "Mountain Hemlock": (27.0, 135.0, 178.0, 4.55, 18.1),
    "Sugar Pine": (170.0, 140.0, 141.0, 6.05, 30.0),
    "White Fir": (65.0, 139.0, 167.0, 4.88, 17.4),
    "Shasta (Noble) Fir": (117.0, 141.0, 159.0, 5.57, 23.0),
    "Grand Fir": (89.0, 147.0, 182.0, 5.24, 20.0),
    "Ponderosa Pine": (135.0, 137.0, 142.0, 6.05, 31.5),
    "Western White Pine": (148.0, 142.0, 133.0, 5.24, 20.0),
    "Lodgepole Pine": (52.0, 157.0, 125.0, 1.84, 11.0),
}

# Table B-66 (Douglas-fir): diameter-class -> (diameter index, selling value
# $/MCF, pond value $/MCF). Pond value = delivered-log value at the mill.
DF_PRICE_DIAMETER = {
    "8-10": (0.58, 2240.0, 1025.0),
    "10-12": (0.63, 2433.0, 1218.0),
    "12-14": (0.68, 2626.0, 1411.0),
}
"""


if __name__ == "__main__":
    main()
